pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                // Change directory to einvoice-bdd before running maven commands
                dir('einovice-bdd') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('einovice-bdd') {
                    sh 'mvn test'
                }
            }
        }
        stage('Archive') {
            steps {
                dir('einovice-bdd') {
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
